### ISSUE TITLE
Saving two media_player states and then trying to restore, result in error

### ISSUE THREAD

**Issue by mcanteri** [PiotrMachowski/Home-Assistant-custom-components-Saver#14]
If I save only one state of the two media players it runs fine, but when I try to save two it goes into error.
My automation first run:
action:
```yaml
  - service: saver.save_state
    data:
      entity_id: media_player.home_mini
  - service: saver.save_state
    data:
      entity_id: media_player.nest_mini
```
then play a message on the group of the two media_player (an announce) and then I try to restore in this way:
```yaml
  - service: saver.restore_state
    data:
      entity_id: media_player.home_mini
      restore_script:
        data:
          media_content_type: >-
            {{
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
            if
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
            is defined and
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
            != none else 'music' }}
          media_content_id: >-
            {{
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
            if
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
            is defined and
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
            != none else 'none' }}
        service: media_player.play_media
        target:
          entity_id: media_player.home_mini
    enabled: true
  - service: saver.restore_state
    data:
      entity_id: media_player.nest_mini
      restore_script:
        data:
          media_content_type: >-
            {{
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
            if
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
            is defined and
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
            != none else 'music' }}
          media_content_id: >-
            {{
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id
            if
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id
            is defined and
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id
            != none else 'none' }}
        service: media_player.play_media
        target:
          entity_id: media_player.nest_mini
    enabled: true
```
and I receive the following error:
```
2022-05-31 18:07:42 ERROR (MainThread) [homeassistant.helpers.script.saver] saver: Error executing script. Unexpected error for call_service at pos 1: string index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 657, in async_play_media
    media_id = async_process_play_media_url(self.hass, media_id)
  File "/usr/src/homeassistant/homeassistant/components/media_player/browse_media.py", line 45, in async_process_play_media_url
    if media_content_id[0] != "/":
IndexError: string index out of range
2022-05-31 18:07:43 ERROR (MainThread) [homeassistant.components.automation.new_automation_2] Alert - Bedroom Light Still On: Error executing script. Unexpected error for call_service at pos 8: string index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1670, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/saver/__init__.py", line 53, in restore_state
    saver_entity.restore(entity_id, restore_script, should_delete)
  File "/config/custom_components/saver/__init__.py", line 117, in restore
    script.run(variables=variables, context=Context())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1416, in run
    asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 657, in async_play_media
    media_id = async_process_play_media_url(self.hass, media_id)
  File "/usr/src/homeassistant/homeassistant/components/media_player/browse_media.py", line 45, in async_process_play_media_url
    if media_content_id[0] != "/":
IndexError: string index out of range
2022-05-31 18:07:43 ERROR (MainThread) [homeassistant.components.automation.new_automation_2] While executing automation automation.new_automation_2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 521, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1670, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/saver/__init__.py", line 53, in restore_state
    saver_entity.restore(entity_id, restore_script, should_delete)
  File "/config/custom_components/saver/__init__.py", line 117, in restore
    script.run(variables=variables, context=Context())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1416, in run
    asyncio.run_coroutine_threadsafe(
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1513, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 405, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 449, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 472, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/cast/media_player.py", line 657, in async_play_media
    media_id = async_process_play_media_url(self.hass, media_id)
  File "/usr/src/homeassistant/homeassistant/components/media_player/browse_media.py", line 45, in async_process_play_media_url
    if media_content_id[0] != "/":
IndexError: string index out of range
```

**Comment by mcanteri** [comment]
I've tried to use "scene" to save (on the fly) and restore the state of the two media_player but it doesn't restore them correctly if they were playing before.

**Comment by PiotrMachowski** [comment]
Does this approach work?
```yaml
  - service: media_player.play_media
    target:
      entity_id: media_player.home_mini
    data:
      media_content_type: >-
        {{
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
        if
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
        is defined and
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
        != none else 'music' }}
      media_content_id: >-
        {{
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
        if
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
        is defined and
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
        != none else 'none' }}
```

**Comment by mcanteri** [comment]
Yes, it works for one entity at a time.

**Comment by PiotrMachowski** [comment]
Ok, but does it work for two of them? Please notice that I haven't use `saver.restore_state` service:
```yaml
  - service: media_player.play_media
    target:
      entity_id: media_player.home_mini
    data:
      media_content_type: >-
        {{
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
        if
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
        is defined and
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
        != none else 'music' }}
      media_content_id: >-
        {{
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
        if
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
        is defined and
        state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id
        != none else 'none' }}
  - service: media_player.play_media
    target:
      entity_id: media_player.nest_mini
    data:
      media_content_type: >-
        {{
        state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
        if
        state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
        is defined and
        state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
        != none else 'music' }}
      media_content_id: >-
        {{
        state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id
        if
        state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id
        is defined and
        state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id
        != none else 'none' }}
```

**Comment by mcanteri** [comment]
Ah sorry, I didn't notice you changed the code, I answered regarding my code. I have to try it and then let you know

**Comment by mcanteri** [comment]
Well, the first always work, but when I run the second it goes in error:

![image](https://user-images.githubusercontent.com/52449704/171404186-bbffe8dd-c00f-4bae-ba92-6fb6d91abbeb.png)

At this point, it is not your code but something related to (maybe) a small difference between Google Home Mini and Nest Mini I guess. The error in the log is:

2022-06-01 14:25:47 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['entity_id']
2022-06-01 14:25:47 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1560167184] Error handling message: value should be a string for dictionary value @ data['entity_id']. Got None (invalid_format)

And I don't know where to go with that.

**Comment by PiotrMachowski** [comment]
You have duplicated entry `service` in your yaml

**Comment by PiotrMachowski** [comment]
You have to omit this service call if media_player was not playing before

**Comment by mcanteri** [comment]
Any idea on how to structure an "if" clause in this case?

**Comment by PiotrMachowski** [comment]
You can do it also this way:
```yaml
  - if:
      - condition: >-
          {{ 
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id is defined 
            and 
            (state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id | string).startswith("/")
          }}
    then:
      - service: media_player.play_media
        target:
          entity_id: media_player.home_mini
        data:
          media_content_type: >-
            {{
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
            if
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
            is defined and
            state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_type
            != none else 'music' }}
          media_content_id: >-
            {{ state_attr('saver.saver','entities')['media_player.home_mini'].attributes.media_content_id }}
  - if:
      - condition: >-
          {{ 
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id is defined 
            and 
            (state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id | string).startswith("/")
          }}
    then:
      - service: media_player.play_media
        target:
          entity_id: media_player.nest_mini
        data:
          media_content_type: >-
            {{
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
            if
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
            is defined and
            state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_type
            != none else 'music' }}
          media_content_id: >-
            {{ state_attr('saver.saver','entities')['media_player.nest_mini'].attributes.media_content_id }}
```
