### ISSUE TITLE
error after update

### ISSUE THREAD

**Issue by evirci** [PiotrMachowski/Home-Assistant-custom-components-Saver#24]
Hi, i have follow errors after upgrade saver in HACS, it seems regard card_mod integration.

Error 1
```
Logger: homeassistant.components.history_stats.helpers
Source: helpers/template.py:570
Integration: history_stats (documentation, issues)
First occurred: 15:59:43 (99 occurrences)
Last logged: 16:10:50

Error parsing template for field start
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 973 more times]
  File "/config/custom_components/saver/__init__.py", line 74, in is_safe_callable
    return (isinstance(obj, (SaverVariableTemplate, SaverEntityTemplate))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in __instancecheck__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/history_stats/helpers.py", line 39, in async_calculate_period
    rendered = template.async_render()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: RecursionError: maximum recursion depth exceeded in __instancecheck__
```

Error 2
```
Logger: homeassistant
Source: helpers/template.py:570
First occurred: 16:01:00 (3 occurrences)
Last logged: 16:09:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 975 more times]
  File "/config/custom_components/saver/__init__.py", line 74, in is_safe_callable
    return (isinstance(obj, (SaverVariableTemplate, SaverEntityTemplate))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in __instancecheck__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/history_stats/coordinator.py", line 93, in _async_update_from_event
    self.async_set_updated_data(await self._history_stats.async_update(event))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/history_stats/data.py", line 67, in async_update
    self._period = async_calculate_period(self._duration, self._start, self._end)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/history_stats/helpers.py", line 39, in async_calculate_period
    rendered = template.async_render()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: RecursionError: maximum recursion depth exceeded in __instancecheck__
```

Error 3
```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/saver/__init__.py:74
Integration: Saver (documentation, issues)
First occurred: 16:08:49 (2 occurrences)
Last logged: 16:08:50

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 232, in _handle_coordinator_update
    self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 206, in _async_update_from_rest_data
    value = template.async_render_with_possible_json_value(value, None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 747, in async_render_with_possible_json_value
    return _render_with_context(self.template, compiled, **variables).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 973 more times]
  File "/config/custom_components/saver/__init__.py", line 74, in is_safe_callable
    return (isinstance(obj, (SaverVariableTemplate, SaverEntityTemplate))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

Error 4
```
Logger: homeassistant.helpers.event
Source: helpers/template.py:570
First occurred: 15:58:57 (283 occurrences)
Last logged: 16:06:28

Error while processing template: Template<template=(mushroom-shape-icon { {% if is_state(config.entity, 'on') %} --card-mod-icon: mdi:connection; {% else %} --card-mod-icon: mdi:connection; {% endif %} display: flex; }) renders=22>
Error while processing template: Template<template=(ha-card { width: 66px; top: -66px; } ha-state-icon { transform-origin: 67% 67%; clip-path: circle(17% at 67% 67%); {% if is_state(config.entity, 'on') %} --icon-color: rgba(var(--rgb-blue), 1); animation: spin 1s linear infinite; {% else %} {% endif %} }) renders=22>
Error while processing template: Template<template=(Settimanale {{ states('sensor.frigorifero_ore_giornaliere') | round(0) }} h/gg {{ states('sensor.frigorifero_settimanale') | round(0) }} kWh {{ states('sensor.frigorifero_settimanale_costo') | round(0) }} €) renders=42>
Error while processing template: Template<template=(Mensile {{ states('sensor.frigorifero_ore_mensile') | round(0) }} h {{ states('sensor.frigorifero_mensile') | round(0) }} kWh {{ states('sensor.frigorifero_mensile_costo') | round(0) }} €) renders=42>
Error while processing template: Template<template=(Annuale {{ states('sensor.frigorifero_ore_annuale') | round(0) }} h {{ states('sensor.frigorifero_annuale') | round(0) }} kWh {{ states('sensor.frigorifero_annuale_costo') | round(0) }} €) renders=42>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 970 more times]
  File "/config/custom_components/saver/__init__.py", line 74, in is_safe_callable
    return (isinstance(obj, (SaverVariableTemplate, SaverEntityTemplate))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in __instancecheck__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: RecursionError: maximum recursion depth exceeded in __instancecheck__
```

Error 5
```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/saver/__init__.py:89
Integration: Saver (documentation, issues)
First occurred: 15:59:06 (1 occurrences)
Last logged: 15:59:06

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 701, in _async_enable_automation
    self._async_detach_triggers = await self._async_attach_triggers(True)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 755, in _async_attach_triggers
    variables = self._trigger_variables.async_render(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script_variables.py", line 62, in async_render
    rendered_variables[key] = template.render_complex(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 239, in render_complex
    return value.async_render(variables, limited=limited, parse_result=parse_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 562, in async_render
    compiled = self._compiled or self._ensure_compiled(limited, strict, log_fn)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 783, in _ensure_compiled
    env = self._env
          ^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 500, in _env
    ret = self.hass.data[wanted_env] = TemplateEnvironment(
                                       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 89, in patched_init
    self.saver_original__init__(hass_param, limited, strict, log_fn)
  File "/config/custom_components/saver/__init__.py", line 89, in patched_init
    self.saver_original__init__(hass_param, limited, strict, log_fn)
  File "/config/custom_components/saver/__init__.py", line 89, in patched_init
    self.saver_original__init__(hass_param, limited, strict, log_fn)
  [Previous line repeated 977 more times]
RecursionError: maximum recursion depth exceeded
```
Erorr 6
```
Logger: homeassistant.components.template.template_entity
Source: components/template/template_entity.py:478
Integration: Template (documentation, issues)
First occurred: 15:58:57 (36 occurrences)
Last logged: 15:59:06

TemplateError('RecursionError: maximum recursion depth exceeded in __instancecheck__') while processing template 'Template<template=({{ (((states('sensor.forno_mensile')|float(default=0)) * (states('input_number.costo_energia')|float(default=0)))) | round(2, default=0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.forno_mensile_costo'
TemplateError('RecursionError: maximum recursion depth exceeded in __instancecheck__') while processing template 'Template<template=({{ (((states('sensor.forno_settimanale')|float(default=0)) * (states('input_number.costo_energia')|float(default=0)))) | round(2, default=0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.forno_settimanale_costo'
TemplateError('RecursionError: maximum recursion depth exceeded in __instancecheck__') while processing template 'Template<template=({{ (((states('sensor.condizionatori_annuali')|float(default=0)) * (states('input_number.costo_energia')|float(default=0)))) | round(2, default=0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.condizionatori_annuali_costo'
TemplateError('RecursionError: maximum recursion depth exceeded in __instancecheck__') while processing template 'Template<template=({{ (((states('sensor.condizionatori_mensili')|float(default=0)) * (states('input_number.costo_energia')|float(default=0)))) | round(2, default=0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.condizionatori_mensili_costo'
TemplateError('RecursionError: maximum recursion depth exceeded in __instancecheck__') while processing template 'Template<template=({{ (((states('sensor.condizionatori_settimanali')|float(default=0)) * (states('input_number.costo_energia')|float(default=0)))) | round(2, default=0) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.condizionatori_settimanali_costo'
```
Error 7
```
Logger: homeassistant.components.sensor
Source: custom_components/saver/__init__.py:74
Integration: Sensore (documentation, issues)
First occurred: 15:58:48 (4 occurrences)
Last logged: 15:58:50

Error adding entities for domain sensor with platform scrape
Error while setting up scrape platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 198, in async_added_to_hass
    self._async_update_from_rest_data()
  File "/usr/src/homeassistant/homeassistant/components/scrape/sensor.py", line 206, in _async_update_from_rest_data
    value = template.async_render_with_possible_json_value(value, None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 747, in async_render_with_possible_json_value
    return _render_with_context(self.template, compiled, **variables).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/saver/__init__.py", line 75, in is_safe_callable
    or self.saver_original_is_safe_callable_old(obj))
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 974 more times]
  File "/config/custom_components/saver/__init__.py", line 74, in is_safe_callable
    return (isinstance(obj, (SaverVariableTemplate, SaverEntityTemplate))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in __instancecheck__
```
If i disable saver component and restart HA, card_mod work well...
Can anyone help me?

**Comment by PiotrMachowski** [comment]
You can downgrade Saver to the previous version, I'll try to fix it soon
