### ISSUE TITLE
Script constructor has been changed

### ISSUE THREAD

**Issue by ilya-fedin** [PiotrMachowski/Home-Assistant-custom-components-Saver#4]
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 206, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 413, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1354, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/saver/__init__.py", line 53, in restore_state
    saver_entity.restore(entity_id, restore_script, should_delete)
  File "/config/custom_components/saver/__init__.py", line 116, in restore
    script = Script(self.hass, restore_script)
TypeError: __init__() missing 2 required positional arguments: 'name' and 'domain'
```

**Comment by PiotrMachowski** [comment]
Fixed in v1.1.1
